application: android-train-track
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /_ah/spi/.*
  script: traintrack_api.APPLICATION

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0