
development:
  adapter: postgresql
  encoding: unicode
  database: trains
  pool: 5
  username: <%= Rails.application.secrets.database_user %>
  password: <%= Rails.application.secrets.database_password %>

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: trains
  pool: 5
  username: <%= Rails.application.secrets.database_user %>
  password: <%= Rails.application.secrets.database_password %>
