
development:
  adapter: mysql2
  encoding: utf8
  database: trains
  pool: 5
  username: <%= ENV['TRAINS_DATABASE_USER'] %>
  password: <%= ENV['TRAINS_DATABASE_PASSWORD'] %>
  host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: trains
  pool: 5
  username: <%= ENV['TRAINS_DATABASE_USER'] %>
  password: <%= ENV['TRAINS_DATABASE_PASSWORD'] %>
  host: localhost
